site_name: todoist-costs
repo_url: https://github.com/anatoly-scherbakov/todoist-costs
repo_name: todoist-costs
copyright: Copyright &copy; 2021 todoist-costs

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - mkdocstrings
  - octadocs
  - octadocs_adr
  - macros:
      modules:
        - octadocs.macros

theme:
  name: material
